"""
Artifact integration and merging utilities
"""
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)


class ArtifactIntegrator:
    """Merge artifacts from multiple agents into final project"""

    def __init__(self):
        self.config = {
            "monorepo": False,
            "generate_readme": True,
            "validate_contracts": True
        }

    async def merge_artifacts(self, job_id: str, artifacts: Dict, config: Dict) -> Dict:
        """Merge code from all agents into final project structure"""
        final_structure = {
            "frontend": artifacts.get("frontend", {}),
            "backend": artifacts.get("backend", {}),
            "infrastructure": artifacts.get("infra", {}),
            "docs": {},
            "config": {}
        }

        if self.config["generate_readme"]:
            final_structure["docs"]["README.md"] = self._generate_readme(job_id, config)

        return final_structure

    def _generate_readme(self, job_id: str, config: Dict) -> str:
        """Generate comprehensive README.md"""
        frontend = config.get('frontend', 'react')
        backend = config.get('backend', 'fastapi')
        cloud = config.get('cloud', 'azure')
        
        readme = "# AI Generated Application - " + job_id + "\n\n"
        readme += "## Overview\n"
        readme += "This application was automatically generated by AI DevFactory.\n\n"
        readme += "## Project Structure\n"
        readme += "- **Frontend**: " + frontend + "\n"
        readme += "- **Backend**: " + backend + "\n"
        readme += "- **Cloud**: " + cloud + "\n\n"
        readme += "## Quick Start\n\n"
        readme += "### Backend Setup\n```bash\ncd backend\npip install -r requirements.txt\npython main.py\n```\n\n"
        readme += "### Frontend Setup\n```bash\ncd frontend\nnpm install\nnpm start\n```\n\n"
        readme += "## API Documentation\n"
        readme += "- Swagger UI: http://localhost:8000/docs\n"
        readme += "- Health Check: http://localhost:8000/health\n\n"
        readme += "## Deployment\nDeploy to " + cloud + " using the infrastructure templates.\n\n"
        readme += "## License\nMIT\n\n---\nGenerated by AI DevFactory"
        
        return readme
