cd ~/AI-DevFactory/backend/orchestrator/utils

# Create a clean working version of artifact_integrator.py
cat > artifact_integrator.py << 'EOF'
"""
Artifact integration and merging utilities
"""
import json
import logging
from typing import Dict, List, Any
from datetime import datetime

logger = logging.getLogger(__name__)


class ArtifactIntegrator:
    """Merge artifacts from multiple agents into final project"""

    def __init__(self):
        self.config = {
            "monorepo": False,
            "generate_readme": True,
            "validate_contracts": True
        }

    async def merge_artifacts(self, job_id: str, artifacts: Dict, config: Dict) -> Dict:
        """
        Merge code from all agents into final project structure
        """
        final_structure = {
            "frontend": artifacts.get("frontend", {}),
            "backend": artifacts.get("backend", {}),
            "infrastructure": artifacts.get("infra", {}),
            "docs": {},
            "config": {}
        }

        # Validate merged structure
        validation = await self._validate_merged_structure(final_structure)

        # Generate README with setup instructions
        if self.config["generate_readme"]:
            final_structure["docs"]["README.md"] = self._generate_readme(job_id, artifacts, config)

        # Add validation results
        final_structure["_validation"] = validation

        return final_structure

    async def _validate_merged_structure(self, structure: Dict) -> Dict:
        """Validate merged structure for conflicts and consistency"""
        issues = []
        warnings = []

        # Check for file conflicts
        all_files = set()
        for section, content in structure.items():
            if isinstance(content, dict):
                for file_path in content.keys():
                    if file_path in all_files:
                        issues.append(f"File conflict: {file_path} appears in multiple sections")
                    all_files.add(file_path)

        return {
            "valid": len(issues) == 0,
            "issues": issues,
            "warnings": warnings,
            "total_files": len(all_files)
        }

    def _generate_readme(self, job_id: str, artifacts: Dict, config: Dict) -> str:
        """Generate comprehensive README.md"""
        readme = f"""# AI Generated Application - {job_id}

## Overview
This application was automatically generated by AI DevFactory.

## Project Structure
- **Frontend**: {config.get('frontend', 'react')}
- **Backend**: {config.get('backend', 'fastapi')}
- **Cloud**: {config.get('cloud', 'azure')}

## Quick Start

### Prerequisites
- Node.js (v18+)
- Python (3.11+)
- Docker (optional)

### Installation

1. **Backend Setup**
```bash
cd backend
pip install -r requirements.txt
python main.py
